In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
pd.set_option('display.max_columns', None)

Data = pd.read_csv("../Data/smalldata.csv")
#Data = pd.read_csv("../Data/300k.csv")
#print(Data.head())

#Steage 1
Selection = ['pokemonId', 'latitude', 'longitude','appearedTimeOfDay', 'appearedHour','appearedMinute',\
             'appearedDay','terrainType', 'closeToWater', 'gymDistanceKm','city', 'continent','weather', 'temperature', \
             'windSpeed', 'windBearing', 'pressure','population_density','urban','suburban','midurban','pokestopDistanceKm','rural']
#Selection = ['pokemonId', 'city','latitude', 'longitude', 'appearedHour','appearedMinute',\
#            'terrainType', 'closeToWater', 'gymDistanceKm','weather', 'temperature', \
#             'windSpeed', 'windBearing', 'pressure',\
#            'class' ]
ReducedData = Data.loc[:, Selection]
ReducedData.head()

In [ ]:
def Convertnumber(Data, field):
    Data[field]= Data[field].astype('category')
    catdict = dict(enumerate(Data[field].cat.categories))
    Data[field] = Data[field].cat.codes
    return catdict, Data

In [ ]:
weatherdict, ReducedData = Convertnumber(ReducedData, 'weather')
waterdict, ReducedData = Convertnumber(ReducedData, 'closeToWater')
appearedTimeOfDaydict, ReducedData = Convertnumber(ReducedData, 'appearedTimeOfDay')
citydict, ReducedData = Convertnumber(ReducedData, 'city')
continentdict, ReducedData = Convertnumber(ReducedData, 'continent')
urbandict, ReducedData = Convertnumber(ReducedData, 'urban')
suburbandict, ReducedData = Convertnumber(ReducedData, 'suburban')
midurbandict, ReducedData = Convertnumber(ReducedData, 'midurban')
ruraldict, ReducedData = Convertnumber(ReducedData, 'rural')
ReducedData.head()

In [ ]:
ReducedData = ReducedData.convert_objects(convert_numeric=True).dropna()

In [10]:
Datamaxtrix = ReducedData.as_matrix()

C:\WorkSpace\Python\Big Data\project\venv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [11]:
x = np.array(Datamaxtrix[:,1:-2])
y = np.array(Datamaxtrix[:,1])
print(np.shape(x))
print(np.shape(y))

(300, 12)
(300,)


In [12]:
sample_numbers = np.shape(x)[0]
randomindex = np.random.choice(sample_numbers, sample_numbers, replace=False)

In [13]:
#Reindex
x = x[randomindex,:]
y = y[randomindex]
#Split into Training and Testing
ratio = 0.7
train_numbers = int(ratio * sample_numbers)
test_numbers = sample_numbers - train_numbers 
feature_train = x[0:train_numbers,:]
feature_test = x[train_numbers:sample_numbers,:]
label_train = y[0:train_numbers]
label_test = y[train_numbers:sample_numbers]
print(np.shape(feature_train),np.shape(label_train))
print(np.shape(feature_test),np.shape(label_test))

(210, 12) (210,)
(90, 12) (90,)


In [14]:
from sklearn.neural_network import MLPClassifier

In [18]:
model= MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(10,20,20,2), random_state=1,verbose=True)
model.fit(feature_train,label_train)
result = model.predict(feature_test)

In [19]:
model.predict_proba(feature_test)

array([[0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646],
       [0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646],
       [0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646],
       ...,
       [0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646],
       [0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646],
       [0.00477605, 0.01900069, 0.00478284, ..., 0.01431864, 0.05237538,
        0.01432646]])

array([16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.,
       16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16., 16.])

In [12]:
result

array([87., 78., 57., ..., 65., 73., 51.])

In [13]:
Predict_city = np.array(list(map(lambda x: catedict3[x],result)))
Predict_city

array(['Tokyo', 'Rome', 'Manila', ..., 'New_York', 'Prague', 'London'],
      dtype='<U12')

In [14]:
Predict_latitude = pd.DataFrame(Predict_city)
Predict_latitude.to_csv("../Result/Predict_city.csv")

In [16]:
city = ReducedData['city']
city.to_csv("../Result/city.csv",header = True)